version: '3.8'

services:
  openai-forward:
    image: mmhk/openai-forward:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"

  app:
    image: mmhk/openai-forward:latest
    restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
      OPENAI_PROJECT_ID: ${OPENAI_PROJECT_ID}
      OPENAI_TARGET_BASE_URL: https://api.openai.com
      OPENAI_MODELS_WHITE_LIST: ${OPENAI_MODELS_WHITE_LIST}
      HTTP_STATIC_DIR: /app/webroot
      PROXY_LISTEN_ADDR: :9000
      PROXY_LOG_LEVEL: debug
      HTTP_DB_DSN: ${HTTP_DB_DSN}
      HTTP_ENABLE_AUTH: "false"
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      AZURE_OPENAI_DEFAULT_MODEL: ${AZURE_OPENAI_DEFAULT_MODEL}
      AZURE_OPENAI_MODEL_MAPPINGS: ${AZURE_OPENAI_MODEL_MAPPINGS}
      OIDC_ISSUER_URL: ${OIDC_ISSUER_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_REDIRECT_URL: ${OIDC_REDIRECT_URL}
      OIDC_DEBUG: "false"
      OIDC_SCOPES: "openid profile email"
      OIDC_ALLOWED_DOMAINS: ${OIDC_ALLOWED_DOMAINS}
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
